name: Daily Property Listings Update

on:
  schedule:
    - cron: '0 1 * * *'  # Run at 1 AM UTC daily
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Update current listings
        run: cd server/functions && node update-sales-data.js

      - name: Update sold listings (append only)
        run: cd server/functions && node update-sold-listings.js

      - name: Build static site
        run: bun run build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.westviewhomesales.com
          username: charles@westviewhomesales.com
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
